os:
  - windows
  - linux
  - osx

language: node_js

node_js:
  - 12
  - 10
  - 8

matrix:
    ## An ENOMEM error occurs with 10.16.0+ under Travis-CI for Windows.
    ## Disable until https://github.com/nodejs/node/issues/25484 is resolved.
    exclude:
        - os: windows
          node_js: 12
        - os: windows
          node_js: 10
    include:
        - os: windows
          node_js: 10.15.0
